In [1]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp313-cp313-win_amd64.whl.metadata (8.6 kB)
Requirement already satisfied: numpy>=1.18.5 in c:\users\karnaveer singh\desktop\decodingml\.venv\lib\site-packages (from gensim) (2.3.2)
Requirement already satisfied: scipy>=1.7.0 in c:\users\karnaveer singh\desktop\decodingml\.venv\lib\site-packages (from gensim) (1.16.1)
Collecting smart_open>=1.8.1 (from gensim)
  Downloading smart_open-7.5.0-py3-none-any.whl.metadata (24 kB)
Collecting wrapt (from smart_open>=1.8.1->gensim)
  Downloading wrapt-2.0.1-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Downloading gensim-4.4.0-cp313-cp313-win_amd64.whl (24.4 MB)
   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   ---------------------------------------- 0.3/24.4 MB ? eta -:--:--
    --------------------------------------- 0.5/24.4 MB 1.0 MB/s eta 0:00:24
   - -------------------------------------- 0.8/24.4 MB 1.1 MB/s eta 0:00:21
   - -------------------------------------- 1.0/24.4 MB 1.2 MB/s eta 0:00:20
   -- ------------------------------------- 1.3/24.4 MB 1.3 MB/s eta 0:00:18
   -- ------------------------------------- 1.6/24.4 MB 1.4 MB/s eta 0:00:17
   --- ------------------------------------ 2.1/24.4 MB 1.4 MB/s eta 0:00:17
   --- ------------------------------------ 2.4/24.4 MB 1.4 MB/s eta 0:00:16
   ---- ----------------------------------- 2.6/24.4 MB 1.4 MB/s eta 0:00:16
   ---- ----------------------------------- 2.9/24.4 MB 1.4 MB/s eta 0:00:16
   ----- ---------------------------------- 3.1/24.4 MB 1.4 MB/s eta 0:00:16
   ----- ---------------------------------- 3.4/24.4 MB 1.3 MB/s eta 0:00:16
   ------ --------------------------------- 3.7/24.4 MB 1.3 MB/s eta 0:00:16
   ------ --------------------------------- 3.9/24.4 MB 1.3 MB/s eta 0:00:16
   ------ --------------------------------- 3.9/24.4 MB 1.3 MB/s eta 0:00:16
   ------ --------------------------------- 4.2/24.4 MB 1.3 MB/s eta 0:00:16
   ------ --------------------------------- 4.2/24.4 MB 1.3 MB/s eta 0:00:16
   ------- -------------------------------- 4.5/24.4 MB 1.2 MB/s eta 0:00:17
   -------- ------------------------------- 5.0/24.4 MB 1.2 MB/s eta 0:00:16
   -------- ------------------------------- 5.0/24.4 MB 1.2 MB/s eta 0:00:16
   -------- ------------------------------- 5.2/24.4 MB 1.2 MB/s eta 0:00:17
   --------- ------------------------------ 5.5/24.4 MB 1.2 MB/s eta 0:00:17
   --------- ------------------------------ 5.5/24.4 MB 1.2 MB/s eta 0:00:17
   --------- ------------------------------ 5.8/24.4 MB 1.1 MB/s eta 0:00:17
   --------- ------------------------------ 5.8/24.4 MB 1.1 MB/s eta 0:00:17
   --------- ------------------------------ 5.8/24.4 MB 1.1 MB/s eta 0:00:17
   --------- ------------------------------ 6.0/24.4 MB 1.0 MB/s eta 0:00:18
   --------- ------------------------------ 6.0/24.4 MB 1.0 MB/s eta 0:00:18
   --------- ------------------------------ 6.0/24.4 MB 1.0 MB/s eta 0:00:18
   --------- ------------------------------ 6.0/24.4 MB 1.0 MB/s eta 0:00:18
   ---------- ----------------------------- 6.3/24.4 MB 958.0 kB/s eta 0:00:19
   ---------- ----------------------------- 6.6/24.4 MB 953.3 kB/s eta 0:00:19
   ----------- ---------------------------- 6.8/24.4 MB 952.0 kB/s eta 0:00:19
   ----------- ---------------------------- 6.8/24.4 MB 952.0 kB/s eta 0:00:19
   ----------- ---------------------------- 7.1/24.4 MB 939.7 kB/s eta 0:00:19
   ------------ --------------------------- 7.3/24.4 MB 948.4 kB/s eta 0:00:18
   ------------ --------------------------- 7.6/24.4 MB 959.1 kB/s eta 0:00:18
   ------------ --------------------------- 7.9/24.4 MB 966.9 kB/s eta 0:00:18
   ------------- -------------------------- 8.1/24.4 MB 972.5 kB/s eta 0:00:17
   ------------- -------------------------- 8.4/24.4 MB 981.0 kB/s eta 0:00:17
   -------------- ------------------------- 8.7/24.4 MB 986.6 kB/s eta 0:00:16
   --------------- ------------------------ 9.2/24.4 MB 1.0 MB/s eta 0:00:16
   --------------- ------------------------ 9.4/24.4 MB 1.0 MB/s eta 0:00:15
   --------------- ------------------------ 9.7/24.4 MB 1.0 MB/s eta 0:00:15
   ---------------- ----------------------- 10.0/24.4 MB 1.0 MB/s eta 0:00:14
   ----------------- ---------------------- 10.5/24.4 MB 1.1 MB/s eta 0:00:14
   ----------------- ---------------------- 10.7/24.4 MB 1.1 MB/s eta 0:00:13
   ----------------- ---------------------- 10.7/24.4 MB 1.1 MB/s eta 0:00:13
   ------------------ --------------------- 11.0/24.4 MB 1.0 MB/s eta 0:00:13
   ------------------ --------------------- 11.3/24.4 MB 1.1 MB/s eta 0:00:13
   ------------------ --------------------- 11.5/24.4 MB 1.1 MB/s eta 0:00:13
   ------------------ --------------------- 11.5/24.4 MB 1.1 MB/s eta 0:00:13
   ------------------- -------------------- 11.8/24.4 MB 1.0 MB/s eta 0:00:13
   ------------------- -------------------- 12.1/24.4 MB 1.0 MB/s eta 0:00:12
   -------------------- ------------------- 12.6/24.4 MB 1.1 MB/s eta 0:00:12
   --------------------- ------------------ 12.8/24.4 MB 1.1 MB/s eta 0:00:11
   --------------------- ------------------ 12.8/24.4 MB 1.1 MB/s eta 0:00:11
   --------------------- ------------------ 13.1/24.4 MB 1.1 MB/s eta 0:00:11
   --------------------- ------------------ 13.4/24.4 MB 1.1 MB/s eta 0:00:11
   --------------------- ------------------ 13.4/24.4 MB 1.1 MB/s eta 0:00:11
   ---------------------- ----------------- 13.6/24.4 MB 1.0 MB/s eta 0:00:11
   ---------------------- ----------------- 13.9/24.4 MB 1.0 MB/s eta 0:00:11
   ----------------------- ---------------- 14.2/24.4 MB 1.0 MB/s eta 0:00:10
   ----------------------- ---------------- 14.4/24.4 MB 1.0 MB/s eta 0:00:10
   ------------------------ --------------- 14.7/24.4 MB 1.1 MB/s eta 0:00:10
   ------------------------ --------------- 14.9/24.4 MB 1.1 MB/s eta 0:00:09
   ------------------------ --------------- 14.9/24.4 MB 1.1 MB/s eta 0:00:09
   ------------------------ --------------- 14.9/24.4 MB 1.1 MB/s eta 0:00:09
   ------------------------ --------------- 15.2/24.4 MB 1.0 MB/s eta 0:00:09
   ------------------------- -------------- 15.5/24.4 MB 1.0 MB/s eta 0:00:09
   ------------------------- -------------- 15.5/24.4 MB 1.0 MB/s eta 0:00:09
   ------------------------- -------------- 15.5/24.4 MB 1.0 MB/s eta 0:00:09
   ------------------------- -------------- 15.5/24.4 MB 1.0 MB/s eta 0:00:09
   ------------------------- -------------- 15.7/24.4 MB 997.1 kB/s eta 0:00:09
   -------------------------- ------------- 16.0/24.4 MB 997.8 kB/s eta 0:00:09
   -------------------------- ------------- 16.3/24.4 MB 1.0 MB/s eta 0:00:09
   --------------------------- ------------ 16.5/24.4 MB 1.0 MB/s eta 0:00:08
   --------------------------- ------------ 16.8/24.4 MB 1.0 MB/s eta 0:00:08
   --------------------------- ------------ 17.0/24.4 MB 1.0 MB/s eta 0:00:08
   ---------------------------- ----------- 17.3/24.4 MB 1.0 MB/s eta 0:00:08
   ---------------------------- ----------- 17.3/24.4 MB 1.0 MB/s eta 0:00:08
   ---------------------------- ----------- 17.6/24.4 MB 1.0 MB/s eta 0:00:07
   ----------------------------- ---------- 17.8/24.4 MB 1.0 MB/s eta 0:00:07
   ----------------------------- ---------- 18.1/24.4 MB 1.0 MB/s eta 0:00:07
   ------------------------------ --------- 18.4/24.4 MB 1.0 MB/s eta 0:00:06
   ------------------------------ --------- 18.6/24.4 MB 1.0 MB/s eta 0:00:06
   ------------------------------ --------- 18.9/24.4 MB 1.0 MB/s eta 0:00:06
   ------------------------------- -------- 19.1/24.4 MB 1.0 MB/s eta 0:00:06
   ------------------------------- -------- 19.4/24.4 MB 1.0 MB/s eta 0:00:05
   -------------------------------- ------- 19.7/24.4 MB 1.0 MB/s eta 0:00:05
   -------------------------------- ------- 19.9/24.4 MB 1.0 MB/s eta 0:00:05
   --------------------------------- ------ 20.2/24.4 MB 1.0 MB/s eta 0:00:05
   --------------------------------- ------ 20.4/24.4 MB 1.0 MB/s eta 0:00:04
   ---------------------------------- ----- 21.0/24.4 MB 1.0 MB/s eta 0:00:04
   ---------------------------------- ----- 21.2/24.4 MB 1.0 MB/s eta 0:00:04
   ----------------------------------- ---- 21.5/24.4 MB 1.0 MB/s eta 0:00:03
   ----------------------------------- ---- 21.8/24.4 MB 1.0 MB/s eta 0:00:03
   ------------------------------------ --- 22.0/24.4 MB 1.0 MB/s eta 0:00:03
   ------------------------------------ --- 22.3/24.4 MB 1.1 MB/s eta 0:00:03
   ------------------------------------- -- 22.8/24.4 MB 1.1 MB/s eta 0:00:02
   ------------------------------------- -- 22.8/24.4 MB 1.1 MB/s eta 0:00:02
   ------------------------------------- -- 23.1/24.4 MB 1.1 MB/s eta 0:00:02
   -------------------------------------- - 23.3/24.4 MB 1.1 MB/s eta 0:00:02
   -------------------------------------- - 23.6/24.4 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  23.9/24.4 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  24.1/24.4 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 24.4/24.4 MB 1.1 MB/s  0:00:23
Downloading smart_open-7.5.0-py3-none-any.whl (63 kB)
Downloading wrapt-2.0.1-cp313-cp313-win_amd64.whl (60 kB)
Installing collected packages: wrapt, smart_open, gensim

   ---------------------------------------- 0/3 [wrapt]
   ------------- -------------------------- 1/3 [smart_open]
   ------------- -------------------------- 1/3 [smart_open]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   -------------------------- ------------- 2/3 [gensim]
   ---------------------------------------- 3/3 [gensim]

Successfully installed gensim-4.4.0 smart_open-7.5.0 wrapt-2.0.1

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [3]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded

In [5]:
king = wv['king']
king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  2.01416016e-02, -1.63085938e-01,  1.35803223e-03,
       -1.44531250e-01, -5.68847656e-02,  4.29687500e-02, -2.46582031e-02,
        1.85546875e-01,  4.47265625e-01,  9.58251953e-03,  1.31835938e-01,
        9.86328125e-02, -1.85546875e-01, -1.00097656e-01, -1.33789062e-01,
       -1.25000000e-01,  2.83203125e-01,  1.23046875e-01,  5.32226562e-02,
       -1.77734375e-01,  8.59375000e-02, -2.18505859e-02,  2.05078125e-02,
       -1.39648438e-01,  2.51464844e-02,  1.38671875e-01, -1.05468750e-01,
        1.38671875e-01,  8.88671875e-02, -7.51953125e-02, -2.13623047e-02,
        1.72851562e-01,  4.63867188e-02, -2.65625000e-01,  8.91113281e-03,
        1.49414062e-01,  3.78417969e-02,  2.38281250e-01, -1.24511719e-01,
       -2.17773438e-01, -1.81640625e-01,  2.97851562e-02,  5.71289062e-02,
       -2.89306641e-02,  1.24511719e-02,  9.66796875e-02, -2.31445312e-01,
        5.81054688e-02,  6.68945312e-02,  7.08007812e-02, -3.08593750e-01,
       -2.14843750e-01,  1.45507812e-01, -4.27734375e-01, -9.39941406e-03,
        1.54296875e-01, -7.66601562e-02,  2.89062500e-01,  2.77343750e-01,
       -4.86373901e-04, -1.36718750e-01,  3.24218750e-01, -2.46093750e-01,
       -3.03649902e-03, -2.11914062e-01,  1.25000000e-01,  2.69531250e-01,
        2.04101562e-01,  8.25195312e-02, -2.01171875e-01, -1.60156250e-01,
       -3.78417969e-02, -1.20117188e-01,  1.15234375e-01, -4.10156250e-02,
       -3.95507812e-02, -8.98437500e-02,  6.34765625e-03,  2.03125000e-01,
        1.86523438e-01,  2.73437500e-01,  6.29882812e-02,  1.41601562e-01,
       -9.81445312e-02,  1.38671875e-01,  1.82617188e-01,  1.73828125e-01,
        1.73828125e-01, -2.37304688e-01,  1.78710938e-01,  6.34765625e-02,
        2.36328125e-01, -2.08984375e-01,  8.74023438e-02, -1.66015625e-01,
       -7.91015625e-02,  2.43164062e-01, -8.88671875e-02,  1.26953125e-01,
       -2.16796875e-01, -1.73828125e-01, -3.59375000e-01, -8.25195312e-02,
       -6.49414062e-02,  5.07812500e-02,  1.35742188e-01, -7.47070312e-02,
       -1.64062500e-01,  1.15356445e-02,  4.45312500e-01, -2.15820312e-01,
       -1.11328125e-01, -1.92382812e-01,  1.70898438e-01, -1.25000000e-01,
        2.65502930e-03,  1.92382812e-01, -1.74804688e-01,  1.39648438e-01,
        2.92968750e-01,  1.13281250e-01,  5.95703125e-02, -6.39648438e-02,
        9.96093750e-02, -2.72216797e-02,  1.96533203e-02,  4.27246094e-02,
       -2.46093750e-01,  6.39648438e-02, -2.25585938e-01, -1.68945312e-01,
        2.89916992e-03,  8.20312500e-02,  3.41796875e-01,  4.32128906e-02,
        1.32812500e-01,  1.42578125e-01,  7.61718750e-02,  5.98144531e-02,
       -1.19140625e-01,  2.74658203e-03, -6.29882812e-02, -2.72216797e-02,
       -4.82177734e-03, -8.20312500e-02, -2.49023438e-02, -4.00390625e-01,
       -1.06933594e-01,  4.24804688e-02,  7.76367188e-02, -1.16699219e-01,
        7.37304688e-02, -9.22851562e-02,  1.07910156e-01,  1.58203125e-01,
        4.24804688e-02,  1.26953125e-01,  3.61328125e-02,  2.67578125e-01,
       -1.01074219e-01, -3.02734375e-01, -5.76171875e-02,  5.05371094e-02,
        5.26428223e-04, -2.07031250e-01, -1.38671875e-01, -8.97216797e-03,
       -2.78320312e-02, -1.41601562e-01,  2.07031250e-01, -1.58203125e-01,
        1.27929688e-01,  1.49414062e-01, -2.24609375e-02, -8.44726562e-02,
        1.22558594e-01,  2.15820312e-01, -2.13867188e-01, -3.12500000e-01,
       -3.73046875e-01,  4.08935547e-03,  1.07421875e-01,  1.06933594e-01,
        7.32421875e-02,  8.97216797e-03, -3.88183594e-02, -1.29882812e-01,
        1.49414062e-01, -2.14843750e-01, -1.83868408e-03,  9.91210938e-02,
        1.57226562e-01, -1.14257812e-01, -2.05078125e-01,  9.91210938e-02,
        3.69140625e-01, -1.97265625e-01,  3.54003906e-02,  1.09375000e-01,
        1.31835938e-01,  1.66992188e-01,  2.35351562e-01,  1.04980469e-01,
       -4.96093750e-01, -1.64062500e-01, -1.56250000e-01, -5.22460938e-02,
        1.03027344e-01,  2.43164062e-01, -1.88476562e-01,  5.07812500e-02,
       -9.37500000e-02, -6.68945312e-02,  2.27050781e-02,  7.61718750e-02,
        2.89062500e-01,  3.10546875e-01, -5.37109375e-02,  2.28515625e-01,
        2.51464844e-02,  6.78710938e-02, -1.21093750e-01, -2.15820312e-01,
       -2.73437500e-01, -3.07617188e-02, -3.37890625e-01,  1.53320312e-01,
        2.33398438e-01, -2.08007812e-01,  3.73046875e-01,  8.20312500e-02,
        2.51953125e-01, -7.61718750e-02, -4.66308594e-02, -2.23388672e-02,
        2.99072266e-02, -5.93261719e-02, -4.66918945e-03, -2.44140625e-01,
       -2.09960938e-01, -2.87109375e-01, -4.54101562e-02, -1.77734375e-01,
       -2.79296875e-01, -8.59375000e-02,  9.13085938e-02,  2.51953125e-01],
      dtype=float32)

In [ ]:
len(king)
## 300 dimensions

300

In [8]:
wv.most_similar('Karn')

[('Aesoph', 0.4868808388710022),
 ('Kotila', 0.4774768054485321),
 ('Diveley', 0.47688236832618713),
 ('Kalal', 0.47249579429626465),
 ('Youngwirth', 0.47228699922561646),
 ('Hymore', 0.4688885807991028),
 ('Heinitz', 0.46631062030792236),
 ('Tokerud', 0.4617624282836914),
 ('DeRoos', 0.46175700426101685),
 ('Poelstra', 0.46104303002357483)]

In [24]:
wv.most_similar('universe')

[('cosmos', 0.7480129599571228),
 ('Universe', 0.7040072083473206),
 ('galaxy', 0.6850187182426453),
 ('universes', 0.6612022519111633),
 ('planets', 0.6195421814918518),
 ('planet', 0.6160004138946533),
 ('observable_universe', 0.6154817342758179),
 ('cosmic', 0.6154016852378845),
 ('multiverse', 0.5912760496139526),
 ('galaxies', 0.5847796201705933)]

In [26]:
wv.similarity('universe','star')

np.float32(0.19593897)

In [27]:
wv.similarity('galaxy','star')

np.float32(0.2611826)

In [31]:
wv.similarity('pizza','sun')

np.float32(0.09923191)

In [32]:
wv.similarity('movie','actor')

np.float32(0.52446246)

In [41]:
wv.similarity('book','books')

np.float32(0.73791784)

In [49]:
vec=wv['king']-wv['man']+wv['woman']
wv.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

Steps for NLP
- preprocessing
- train test split 
- vectorizing (prevent data leakage)
- train model acc to the vectorizing method used 
- naive for (bow and tf-idf) and random forest for word2vec

In [58]:
import pandas as pd
df = pd.read_csv (r'C:\Users\Karnaveer Singh\Desktop\DecodingML\spamhamdata.csv', sep='\t', header=None, names=['label', 'text'])

In [59]:
df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [60]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Karnaveer
[nltk_data]     Singh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [61]:

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [ ]:

corpus=[]
##lower case , stopword removal , stemming
for i in range(0,len(df)):
    review=re.sub('[^a-zA-z]',' ',df['text'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

In [63]:
y=pd.get_dummies(df['label'])

In [64]:
y

        ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [66]:
y=y.iloc[:,0].values

In [67]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=0.20)

In [68]:
X_train

['enjoy urself tmr',
 'dear hero leav qatar tonit apt opportun pl keep touch lt email gt kerala',
 'think chennai well settl',
 'sorri call later',
 'congrat year special cinema pass call c suprman v matrix starwar etc free bx ip pm dont miss',
 'much u tri get',
 'call carlo phone vibrat act might hear text',
 'santa call would littl one like call santa xma eve call book time',
 'much r will pay',
 'oh phone phone disconnect',
 'k u bore come home',
 'world famamu',
 'hhahhaahahah rofl wtf nig leonardo room someth',
 'tick tick tick babe',
 'k marrow come class',
 'go write msg put dictionari mode cover screen hand press lt gt gentli remov ur hand interest',
 'aight still want get money',
 'ha us e thing got tv watch u thk go tonight u alreadi haf smth mind',
 'kaiez enjoy ur tuition gee thk e second option sound beta go yan jiu den msg u',
 'sorri mate phone didnt write love kate',
 'hi test lt gt rd',
 'freez crave ice fml',
 'still west coast haiz take forev come back',
 'cant pick phone right pl send messag',
 'ok lor msg b u call',
 'late call tomorrow morn take care sweet dream u ummifi bye',
 'privat account statement show un redeem point call identifi code expir',
 'size eleph tablet u shove um ur ass',
 'stop club tone repli stop mix see tone com enjoy html term club tone cost gbp week mfl po box mk wt',
 'free st week entri textpod chanc win gb ipod cash everi wk txt vpod ts cs www textpod net custcar',
 'cool breez bright sun fresh flower twitter bird wait wish u goodmorn amp nice day',
 'lol ye friendship hang thread caus u buy stuff',
 'roger probabl go rem',
 'hi mobil lt gt ad contact list www fullonsm com great place send free sm peopl visit fullonsm com',
 'love holiday monday feel even go dentist hour',
 'everywher dirt floor window even shirt sometim open mouth come flow dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done becom one',
 'accordingli repeat text word ok mobil phone send',
 'v skint fanci bevi waz gona go meet othr spoon jst bin watchng planet earth sofa v comfey dont make hav gd night',
 'nd time tri contact u u prize claim easi call p per minut bt nation rate',
 'ye repli mail go manag offic later plu bank later also wednesday',
 'dear u invit xchat final attempt contact u txt chat p msgrcvdhg suit land row w j hl ldn yr',
 'free st week nokia tone ur mob everi week txt nokia get txting tell ur mate www getz co uk pobox w wq norm p tone',
 'hey happen de alright',
 'gonna ring weekend wot',
 'worri hope photo shoot went well spif fun workag',
 'yunni goin late',
 'k k pa lunch aha',
 'dizzamn aight ask suitem get back',
 'come back thursday yay gonna ok get money cheer oh yeah everyth alright how school call work',
 'come',
 'happi new year u',
 'go take babe',
 'well still bit left guy want tonight',
 'ur balanc next question complet landmark big bob b barri c ben text b c good luck',
 'sir wait mail',
 'b go esplanad fr home',
 'yup remb think book',
 'prob send email',
 'got ur favorit oyster n got favorit sashimi ok lar dun say alreadi wait ur stomach start rumbl',
 'pleas give us connect today lt decim gt refund bill',
 'yep derek hous see sunday lt',
 'k sent',
 'good afternoon sunshin dawn day refresh happi aliv breath air smile think love alway',
 'pride almost lt gt year old takin money kid suppos deal stuff grownup stuff tell',
 'privat account statement show un redeem point call identifi code expir',
 'yeah ju rite',
 'nokia get win free auction take part send nokia hg suit land row w jhl',
 'usual iam fine happi amp well',
 'also rememb bead come ever',
 'love u littl poci bell sorri love u',
 'mmmmm sooooo good wake word morn love mmmm fuck love lion devour kiss across sea',
 'sorri dude dont know forgot even dan remind sorri hope guy fun',
 'world suffer lot violenc bad peopl silenc good peopl gud night',
 'appl day doctor tulsi leaf day cancer lemon day fat cup milk day bone problm litr watr day diseas snd th u care',
 'start dont stop pray good idea anyth see help guy forward link',
 'oi ami parchi na kicchu kaaj kort iccha korch na phone ta tul na plz plz',
 'babe got enough money pick bread milk give back get home',
 'msg mobil content order resent previou attempt fail due network error queri customersqueri netvis uk com',
 'hot live fantasi call p per min ntt ltd po box croydon cr wb k',
 'ya srsli better yi tho',
 'squeeeeez christma hug u lik frndshp den hug back u get u r cute u r luvd u r lucki none peopl hate u',
 'ok lor u wan go look u',
 'thk shd ok said plu minu leav line paragraph',
 'let math good',
 'sound good keep post',
 'nooooooo gonna bore death day cabl internet outag',
 'import custom servic announc call freephon',
 'call number avail appoint ask connect call wahe fathima',
 'still custom place',
 'scienc tell chocol melt sunlight pleas walk sunlight bcoz want loss sweet friend',
 'yup still coffe wif fren fren drove give lift',
 'say happen',
 'kothi print marandratha',
 'yup song bro creativ neva test qualiti said check review onlin',
 'gonna get rimac access',
 'today vodafon number end select receiv award number match call receiv award',
 'sorri left phone upstair ok might hectic would bird one fell swoop date',
 'anyth lor u decid',
 'work mon thur sat cant leh book liao day u free',
 'dont know support ass srt thnk think ps play usb',
 'today sorri day ever angri ever misbehav hurt plz plz slap urself bcoz ur fault basic good',
 'samu shoulder yet',
 'chang fb jaykwon thuglyf falconerf',
 'revers cheat mathemat',
 'pl pl send mail know rel come deliv know cost risk benefit anyth els thank',
 'aight hit get cash',
 'go lunch',
 'email yifeng part oredi get fr',
 'babe said hour almost internet',
 'leav wif lar wan carri meh heavi da num familiar',
 'plan yet',
 'ok problem yup go sch rem correctli',
 'nutter cutter ctter cttergg cttargg ctargg ctagg ie',
 'sir wait letter',
 'work technic support voic process',
 'well gener price lt gt oz let know much want',
 'oooh got plenti',
 'oh babi hous come dont new pictur facebook',
 'mani compani tell languag',
 'prefer free day tue wed fri oso ask workin lor',
 'erm ill pick pm give enough time get park',
 'love work home',
 'mani lick take get center tootsi pop',
 'ok way railway',
 'mmmmm love wake word morn miss love hope day goe well happi wait us togeth',
 'also tell said happi birthday',
 'sir need velusami sir date birth compani bank facil detail',
 'call germani penc per minut call fix line via access number prepay direct access www telediscount co uk',
 'seem unnecessarili affection',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'take someth pain move howev side next hr see doctor',
 'ok chines food way get fat pay lipo',
 'happi new year hope good semest',
 'noe ben go',
 'sorri help',
 'u love someon dont make love u much u love much dont want love anyon except gud nit',
 'imagin life without see fast u search worri l alway disturb u goodnoon',
 'want sent lt gt mesag today that sorri hurt',
 'tell dear happen talk like alian',
 'sunshin hol claim ur med holiday send stamp self address envelop drink us uk po box bray wicklow eir quiz start saturday unsub stop',
 'haha yeah see sec',
 'one day crab run sea shore wave came n clear footprint crab crab ask frnd r u clear beauti footprint wave repli fox follow ur footprint catch that clear frndsship never let u dwn gud nyt',
 'spook mob halloween collect logo pic messag plu free eeri tone txt card spook zed p per logo pic',
 'greatest test courag earth bear defeat without lose heart gn tc',
 'ye princess go make moan',
 'dear voucher holder claim week offer pc pleas go http www wtlp co uk text ts cs appli',
 'good r u work',
 'guy go see movi side',
 'u nokia plu free digit camera u get u win free auction take part send nokia pobox tcr w',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'yeah probabl',
 'k see k',
 'put sign choos number pin show right',
 'ok day make dinner tonit invit',
 'still otsid le u come morrow maga',
 'congrat nokia video camera phone call call cost ppm ave call min vari mobil close post bcm ldn wc n xx',
 'told go got drunk',
 'u ned convinc tht possibl witot hurt feel main',
 'long fuckin showr',
 'wen ur lovabl bcum angri wid u dnt take serious coz angri childish n true way show deep affect care n luv kettoda manda nice day da',
 'k actual guy meet sunoco howard right way',
 'r u meet da ge nite tmr',
 'slow use biola fne',
 'send new number',
 'oh get even u u',
 'know mood today',
 'hi jess dont know work call u im home eve xxx',
 'kindli send one flat lt decim gt today',
 'that cool want pleas',
 'thought see',
 'like shake booti danc floor',
 'one best dialogu cute reltnship wen die dont come near bodi bcoz hand may come wipe ur tear time gud ni',
 'hey r watch movi tonight prob b home earli',
 'complet degre use join financ',
 'laptop take',
 'yeah get random dude need chang info sheet parti lt gt never studi safe',
 'would u fuckin believ didnt know thur pre book cancel need b sack',
 'miss call miss call khelat kintu opponent miss call dhort lage that rule one great phone receiv qualiti win',
 'otherwis part time job na tuition',
 'take care n get well soon',
 'parent kidz friend n colleagu scream surpris wait sofa nake',
 'win realli side long time',
 'k eng rock ash',
 'dont think turn like randomlli within min open',
 'look ami ure beauti intellig woman like u lot know u like like worri',
 'thank wonder',
 'santa call would littl one like call santa xma eve call book time call ppm last min c www santacal com',
 'escap theatr go watch kavalan minut',
 'cant think anyon spare room top head',
 'like person size',
 'also cbe pay',
 'k k give treat',
 'small problem auction punj ask tiwari',
 'kalli home ground amla home town durban',
 'guess got screwd',
 'joy father john john name joy father mandan',
 'come guoyang go n tell u told',
 'let know contact settl room let know ok',
 'end might still vomit okay everyth come',
 'argh g spotti anyway thing rememb research provinc sterl problem free place look',
 'ok',
 'send greet joy happi gr even',
 'left vagu said would inform person account delay rent discuss hous agenc rent anoth place check onlin place around usc lt gt',
 'hide anythi keep distanc',
 'met alex nichol middl school turn deal',
 'hope know still mad',
 'yeah see',
 'ujhhhhhhh comput ship address sandiago parantella lane wtf poop',
 'ok anybodi ask abt u tel p',
 'fine bitch later',
 'news hassl get weed week andr money haughaighgtujhyguj',
 'master buy bb co sale bf',
 'hey darlin pick u colleg u tell wen mt love pete xx',
 'aiyar sorri lor forgot tell u',
 'quit lor dun tell wait get complac',
 'tmrw im finish door',
 'ask say pleas messag',
 'ur chanc win wkli shop spree txt shop c www txt shop com custcar x p wk',
 'leav hous',
 'anyth lor',
 'probabl money worri thing come due sever outstand invoic work two three month ago',
 'k delet contact',
 'watch tv lor funni bluff wat izzit thk imposs us',
 'tmr timin still da wat co got lesson',
 'costa del sol holiday await collect call toclaim sae tc pobox stockport sk xh cost pm max min',
 'sent scream moan bed princess',
 'free entri weekli comp send word win c www txttowin co uk',
 'tkt euro cup final cash collect call b pobox ppm',
 'pm cost p',
 'ok come home',
 'theyr lot place hospit medic place safe',
 'need get',
 'good afternoon loverboy goe day luck come way think sweeti send love across sea make smile happi',
 'update_now mth half price orang line rental min call mobileupd call optout j q',
 'ok ok ok what ur today plan',
 'u laugh realli loud u talk spontan u dont care other feel u probabl dear amp best friend goodeven dear',
 'new messag call',
 'fight world easi u either win lose bt fightng close u dificult u lose u lose u win u still lose',
 'one issu california okay snow manag',
 'hey da cool iknow wellda peril studentfinanci crisi spk u l r',
 'drive train',
 'ok',
 'yeah lol luckili star role like',
 'kalli wont bat nd inning',
 'mobi pub quiz win high street prize u know new duchess cornwal txt first name unsub stop sp',
 'know peopl still town',
 'respond',
 'hi neva worri bout da truth coz truth lead ur heart least uniqu person like u deserv sleep tight morn',
 'ok lor',
 'told everyth stop dont let get dehydr',
 'yup',
 'back bit long co accid divert via wadebridg brilliant weekend thank speak soon lot love',
 'ya ok dinner',
 'ard like dat lor juz meet mrt station dun haf come',
 'joy father john john name joy father mandan',
 'good afternoon love good see word ym get tm smart move slave smile drink coffe await',
 'pick ur fone u dumb',
 'congrat mobil g videophon r call videochat wid ur mate play java game dload polyh music nolin rentl bx ip pm',
 'sorri call later',
 'ye reg ciao',
 'u sleep go take haha got spi wat onlin check n repli mail lor',
 'gonna way specif',
 'btw regard realli tri see anyon els th guy commit random dude',
 'dear reach room',
 'search happi main sourc unhappi accept life way come u find happi everi moment u live',
 'wake afternoon sup',
 'lmao nice',
 'infact happi new year see',
 'ok lor anyway thk cant get ticket co like quit late alreadi u wan go look ur fren darren wif',
 'ay wana meet sat wkg sat',
 'privat account statement show unredeem bonu point claim call identifi code expir',
 'back amp pack car let know room',
 'get ticket walsal tue th march mate get sat ill pay treat want go txt bak terri',
 'askd u question hour answer',
 'bday real april',
 'luck catch put',
 'babe need advic',
 'edison rightli said fool ask question wise man answer know us speechless viva gm gn ge gnt',
 'would realli appreci call need someon talk',
 'x cours yr messag messeng lik r send',
 'time week ryan',
 'bear pic nick tom pete dick fact type tri gay chat photo upload call p min stop text call',
 'know pl open back',
 'swt thought nver get tire littl thing lovabl person coz somtim littl thing occupi biggest part heart gud ni',
 'got got colour lor one colour quit light n e darker lor actual done style hair',
 'watch tv lor',
 'left dessert u wan go suntec look u',
 'moon come color dream star make music sm give warm peac sleep good night',
 'nice nice work',
 'dont hesit know second time weak like keep notebook eat day anyth chang day sure noth',
 'thank u',
 'kalli dismissi nd test',
 'buy space invad chanc win orig arcad game consol press game arcad std wap charg see co uk game term set purchas',
 'si catch e show e afternoon watch w c u wan watch today tmr lor',
 'got thing may pub later',
 'mm ye dear look hug p',
 'yay final lol miss cinema trip last week',
 'win shop spree everi week start play text store skilgm tsc winawk age perweeksub',
 'yeah abl text readi meet',
 'worri sure get',
 'dunno lei might b eatin wif fren wan eat wait lar',
 'ye place town meet excit adult singl uk txt chat p msg',
 'raviyog peripher bhayandar east',
 'ok knacker came home went sleep good full time work lark',
 'ok tell half hr b u come need prepar',
 'gal n boy walk park gal hold ur hand boy u think would run away gal jst wana c feel walk heaven princ gn',
 'yup thk e shop close lor',
 'saw ron burgundi captain parti boat yeah',
 'ok lor buy wat',
 'brother transfer lt gt lt gt pa',
 'want tell bad feel basic time text late need drug',
 'headin toward busetop',
 'know need get hotel got invit apologis cali sweet come english bloke weddin',
 'want explicit sex sec ring cost p min gsex pobox wc n xx',
 'may call later pl',
 'agre stop thinkin ipad pleas ask macho question',
 'lol real told dad cancer',
 'want pleas insid outsid bedroom',
 'yo yo yo byatch whassup',
 'heart empti without love mind empti without wisdom eye r empti without dream amp life empti without frnd alwi touch good night amp sweet dream',
 'weather',
 'good let thank god pleas complet drug lot water beauti day',
 'remind get shall',
 'p per min call germani bt line p per min check planettalkinst com info c text stop opt',
 'want send virtual hug need one',
 'stand away heart ach without wonder crave',
 'k readi lt gt',
 'warner villag c colin farrel swat wkend warner villag get free med popcorn show msg ticket kiosk valid c c kiosk repli soni mre film offer',
 'fantasi footbal back tv go sky gamestar sky activ play k dream team score start saturday regist sky opt',
 'ye princess want pleas everi night wish command',
 'wherr boytoy',
 'urgent mobil number award prize guarante call land line claim valid hr',
 'nah im goin wrk j wot bout u',
 'hey glad u r better hear u treat urself digi cam good r pm fab new year c u coupla wk',
 'pay first lar da stock comin',
 'enufcredeit tocal shall ileav uni get bu yor hous',
 'come u got noth',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mu like lt gt second',
 'went project centr',
 'might accid tookplac somewher ghodbandar rd traffic move slove plz slip amp worri',
 'know thing wrong everyso often panick start goin bout bein good enough',
 'intrepid duo great time see soon',
 'taxt massag tie po argh ok lool',
 'know taj mahal symbol love lesser known fact mumtaz shahjahan th wife wife shahjahan kill mumtaz husband marri mumtaz die lt gt th deliveri marri mumtaz sister question aris hell love great hari',
 'thanx day u r goodmat think ur rite sari asusu u cheer love u franyxxxxx',
 'wonder world th th ur style th ur smile th ur person rd ur natur nd ur sm st ur love friendship good morn dear',
 'make sure alex know birthday fifteen minut far concern',
 'say die man feel sad go want know would probabl gone late night',
 'hope settl new school year wishin gr day',
 'wat time r go xin hostel',
 'ta daaaaa home babe still',
 'u secret admir reveal think u r special call opt repli reveal stop per msg recd cust care',
 'sorri pain ok meet anoth night spent late afternoon casualti mean done stuff moro includ time sheet sorri',
 'parent kidz friend n colleagu scream surpris wait sofa nake',
 'forgotten might coupl buck send tomorrow k love ya',
 'sure thing big man hockey elect go longer hour though',
 'releas anoth italian one today cosign option',
 'day ask anand number',
 'u attend ur drive lesson mani time wk n day',
 'plz tell an bslvyl sent via fullonsm com',
 'last thing ever want hurt think would laugh embarass delet tag keep go far knew even fact even felt like would hurt show realli know messi wednesday bad problem time clean choos skype take pictur sleep want go mind thing make bed throw laundri top friend hous embarass underwear bra strewn bed pillow floor someth els use good least make bed',
 'offic around pm go hospit',
 'k give kvb acc detail',
 'done sorri hope next space give everyth want rememb furnitur around move lock lock leav key jenn',
 'kind took garag centr part exhaust need replac part order n take fix tomo morn',
 'shuhui say chang suntec steamboat u noe r u',
 'probabl want pick',
 'sorri meet call later',
 'dont thnk wrong call us',
 'probabl coupl hour top',
 'even friend priest call',
 'shore takin bu',
 'wife knew time murder exactli',
 'hey sexi bun day word morn ym think',
 'gonna pick burger way home even move pain kill',
 'wil lt gt minut got space',
 'right think',
 'hank lotsli',
 'remain unconvinc elabor test willpow',
 'loan purpos homeown tenant welcom previous refus still help call free text back help',
 'hi u decid wot get bday ill prob ju get voucher frm virgin sumf',
 'come home want u miser',
 'hand phone chat wit u',
 'still look car buy gone drive test yet',
 'oh ho first time u use type word',
 'good day mine realli busi much tomorrow night',
 'hi wkend ok journey terribl wk good huge back log mark',
 'ye pleas swim',
 'find way includ detail',
 'still come tonight',
 'uncl atlanta wish guy great semest',
 'win urgent mobil number award prize guarante call land line claim valid hr ppm',

In [69]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,ngram_range=(1,2))
X_train=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [70]:
from sklearn.naive_bayes import MultinomialNB

In [ ]:
model=MultinomialNB().fit(X_train,y_train)

In [72]:
y_pred=model.predict(X_test)

In [74]:
from sklearn.metrics import accuracy_score,classification_report
accuracy_score(y_test,y_pred)

0.9829596412556054

In [ ]:
##CAN TRY TD-IDF AS WELL
# from sklearn.feature_extraction.text import TfidfVectorizer
# tv=TfidfVectorizer(max_features=2500,ngram_range=(1,2))
# X_train=tv.fit_transform(X_train).toarray()
# X_test=tv.transform(X_test).toarray()

Trying word2vec model

In [156]:

from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [157]:
corpus = []
for i in range(0, len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['text'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)
    
#corpus ->[sent, sent , sent....]

In [158]:
# (2, ['hello','world'], "Hello world")
# (0, [], " ")
# (4, ['this','is','a','test'], "This is a test")
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, df['text']) if i<1]

# map(len,corpus) --> maps leength to each element of corpus 
# ':) ' was converted to null string in corpus after preprocessng

## hence 3 data points were deleted

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [159]:

from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [160]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

# Lowercases text
# Removes punctuation
# Removes numbers
# Tokenizes into words
# Removes very short tokens

In [100]:
words ##(for each sentence array)

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'speak',
  'with',
  'me',
  'they',
  'treat',
  'me',
  'like',
  'aid',
  'patent'],
 ['per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'your',
  'callertune',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'you',
  'have',
  'been',
  'selected',
  'to',
  'receivea',
  'prize',
  'reward',
  'to',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hour',
  'only'],
 ['had',
  'your',
  'mobile',
  'month',
  'or',
  'more',
  'entitled',
  'to',
  'update',
  'to',
  'the',
  'latest',
  'colour',
  'mobile',
  'with',
  'camera',
  'for',
  'free',
  'call',
  'the',
  'mobile',
  'update',
  'co',
  'free',
  'on'],
 ['gonna',
  'be',
  'home',
  'soon',
  'and',
  'don',
  'want',
  'to',
  'talk',
  'about',
  'this',
  'stuff',
  'anymore',
  'tonight',
  've',
  'cried',
  'enough',
  'today'],
 ['six',
  'chance',
  'to',
  'win',
  'cash',
  'from',
  'to',
  'pound',
  'txt',
  'csh',
  'and',
  'send',
  'to',
  'cost',
  'day',
  'day',
  'tsandcs',
  'apply',
  'reply',
  'hl',
  'info'],
 ['urgent',
  'you',
  'have',
  'won',
  'week',
  'free',
  'membership',
  'in',
  'our',
  'prize',
  'jackpot',
  'txt',
  'the',
  'word',
  'claim',
  'to',
  'no',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  'ldnw',
  'rw'],
 ['ve',
  'been',
  'searching',
  'for',
  'the',
  'right',
  'word',
  'to',
  'thank',
  'you',
  'for',
  'this',
  'breather',
  'promise',
  'wont',
  'take',
  'your',
  'help',
  'for',
  'granted',
  'and',
  'will',
  'fulfil',
  'my',
  'promise',
  'you',
  'have',
  'been',
  'wonderful',
  'and',
  'blessing',
  'at',
  'all',
  'time'],
 ['have', 'date', 'on', 'sunday', 'with', 'will'],
 ['to',
  'use',
  'your',
  'credit',
  'click',
  'the',
  'wap',
  'link',
  'in',
  'the',
  'next',
  'txt',
  'message',
  'or',
  'click',
  'here',
  'http',
  'wap',
  'com',
  'qjkgighjjgcbl'],
 ['oh', 'watching', 'here'],
 ['eh',
  'remember',
  'how',
  'spell',
  'his',
  'name',
  'yes',
  'did',
  'he',
  'naughty',
  'make',
  'until',
  'wet'],
 ['fine',
  'if',
  'that',
  'the',
  'way',
  'feel',
  'that',
  'the',
  'way',
  'it',
  'gota'],
 ['england',
  'macedonia',
  'dont',
  'miss',
  'the',
  'goal',
  'team',
  'news',
  'txt',
  'ur',
  'national',
  'team',
  'to',
  'eg',
  'england',
  'to',
  'try',
  'wale',
  'scotland',
  'txt',
  'poboxox',
  'wq'],
 ['is', 'that', 'seriously', 'how', 'you', 'spell', 'his', 'name'],
 ['going', 'to', 'try', 'for', 'month', 'ha', 'ha', 'only', 'joking'],
 ['so', 'pay', 'first', 'lar', 'then', 'when', 'is', 'da', 'stock', 'comin'],
 ['aft',
  'finish',
  'my',
  'lunch',
  'then',
  'go',
  'str',
  'down',
  'lor',
  'ard',
  'smth',
  'lor',
  'finish',
  'ur',
  'lunch',
  'already'],
 ['ffffffffff',
  'alright',
  'no',
  'way',
  'can',
  'meet',
  'up',
  'with',
  'you',
  'sooner'],
 ['just',
  'forced',
  'myself',
  'to',
  'eat',
  'slice',
  'really',
  'not',
  'hungry',
  'tho',
  'this',
  'suck',
  'mark',
  'is',
  'getting',
  'worried',
  'he',
  'know',
  'sick',
  'when',
  'turn',
  'down',
  'pizza',
  'lol'],
 ['lol', 'your', 'always', 'so', 'convincing'],
 ['did',
  'you',
  'catch',
  'the',
  'bus',
  'are',
  'you',
  'frying',
  'an',
  'egg',
  'did',
  'you',
  'make',
  'tea',
  'are',
  'you',
  'eating',
  'your',
  'mom',
  'left',
  'over',
  'dinner',
  'do',
  'you',
  'feel',
  'my',
  'love'],
 ['back',
  'amp',
  'we',
  're',
  'packing',
  'the',
  'car',
  'now',
  'll',
  'let',
  'you',
  'know',
  'if',
  'there',
  'room'],
 ['ahhh',
  'work',
  'vaguely',
  'remember',
  'that',
  'what',
  'doe',
  'it',
  'feel',
  'like',
  'lol'],
 ['wait',
  'that',
  'still',
  'not',
  'all',
  'that',
  'clear',
  'were',
  'you',
  'not',
  'sure',
  'about',
  'me',
  'being',
  'sarcastic',
  'or',
  'that',
  'that',
  'why',
  'doesn',
  'want',
  'to',
  'live',
  'with'],
 ['yeah',
  'he',
  'got',
  'in',
  'at',
  'and',
  'wa',
  'apologetic',
  'had',
  'fallen',
  'out',
  'and',
  'she',
  'wa',
  'actin',
  'like',
  'spoilt',
  'child',
  'and',
  'he',
  'got',
  'caught',
  'up',
  'in',
  'that',
  'till',
  'but',
  'we',
  'won',
  'go',
  'there',
  'not',
  'doing',
  'too',
  'badly',
  'cheer',
  'you'],
 ['tell', 'me', 'anything', 'about', 'you'],
 ['for',
  'fear',
  'of',
  'fainting',
  'with',
  'the',
  'of',
  'all',
  'that',
  'housework',
  'you',
  'just',
  'did',
  'quick',
  'have',
  'cuppa'],
 ['thanks',
  'for',
  'your',
  'subscription',
  'to',
  'ringtone',
  'uk',
  'your',
  'mobile',
  'will',
  'be',
  'charged',
  'month',
  'please',
  'confirm',
  'by',
  'replying',
  'yes',
  'or',
  'no',
  'if',
  'you',
  'reply',
  'no',
  'you',
  'will',
  'not',
  'be',
  'charged'],
 ['yup',
  'ok',
  'go',
  'home',
  'look',
  'at',
  'the',
  'timing',
  'then',
  'msg',
  'again',
  'xuhui',
  'going',
  'to',
  'learn',
  'on',
  'nd',
  'may',
  'too',
  'but',
  'her',
  'lesson',
  'is',
  'at',
  'am'],
 ['oops', 'll', 'let', 'you', 'know', 'when', 'my', 'roommate', 'done'],
 ['see', 'the', 'letter', 'on', 'my', 'car'],
 ['anything', 'lor', 'decide'],
 ['hello',
  'how',
  'you',
  'and',
  'how',
  'did',
  'saturday',
  'go',
  'wa',
  'just',
  'texting',
  'to',
  'see',
  'if',
  'you',
  'decided',
  'to',
  'do',
  'anything',
  'tomo',
  'not',
  'that',
  'trying',
  'to',
  'invite',
  'myself',
  'or',
  'anything'],
 ['pls',
  'go',
  'ahead',
  'with',
  'watt',
  'just',
  'wanted',
  'to',
  'be',
  'sure',
  'do',
  'have',
  'great',
  'weekend',
  'abiola'],
 ['did',
  'forget',
  'to',
  'tell',
  'you',
  'want',
  'you',
  'need',
  'you',
  'crave',
  'you',
  'but',
  'most',
  'of',
  'all',
  'love',
  'you',
  'my',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummy'],
 ['rodger',
  'burn',
  'msg',
  'we',
  'tried',
  'to',
  'call',
  'you',
  're',
  'your',
  'reply',
  'to',
  'our',
  'sm',
  'for',
  'free',
  'nokia',
  'mobile',
  'free',
  'camcorder',
  'please',
  'call',
  'now',
  'for',
  'delivery',
  'tomorrow'],
 ['who', 'are', 'you', 'seeing'],
 ['great',
  'hope',
  'you',
  'like',
  'your',
  'man',
  'well',
  'endowed',
  'am',
  'lt',
  'gt',
  'inch'],
 ['no', 'call', 'message', 'missed', 'call'],
 ['didn', 'you', 'get', 'hep', 'immunisation', 'in', 'nigeria'],
 ['fair', 'enough', 'anything', 'going', 'on'],
 ['yeah',
  'hopefully',
  'if',
  'tyler',
  'can',
  'do',
  'it',
  'could',
  'maybe',
  'ask',
  'around',
  'bit'],
 ['don',
  'know',
  'how',
  'stubborn',
  'am',
  'didn',
  'even',
  'want',
  'to',
  'go',
  'to',
  'the',
  'hospital',
  'kept',
  'telling',
  'mark',
  'not',
  'weak',
  'sucker',
  'hospital',
  'are',
  'for',
  'weak',
  'sucker'],
 ['what',
  'you',
  'thinked',
  'about',
  'me',
  'first',
  'time',
  'you',
  'saw',
  'me',
  'in',
  'class'],
 ['gram',
  'usually',
  'run',
  'like',
  'lt',
  'gt',
  'half',
  'eighth',
  'is',
  'smarter',
  'though',
  'and',
  'get',
  'you',
  'almost',
  'whole',
  'second',
  'gram',
  'for',
  'lt',
  'gt'],
 ['fyi',
  'ha',
  'ride',
  'early',
  'tomorrow',
  'morning',
  'but',
  'he',
  'crashing',
  'at',
  'our',
  'place',
  'tonight'],
 ['wow',
  'never',
  'realized',
  'that',
  'you',
  'were',
  'so',
  'embarassed',
  'by',
  'your',
  'accomodations',
  'thought',
  'you',
  'liked',
  'it',
  'since',
  'wa',
  'doing',
  'the',
  'best',
  'could',
  'and',
  'you',
  'always',
  'seemed',
  'so',
  'happy',
  'about',
  'the',
  'cave',
  'sorry',
  'didn',
  'and',
  'don',
  'have',
  'more',
  'to',
  'give',
  'sorry',
  'offered',
  'sorry',
  'your',
  'room',
  'wa',
  'so',
  'embarassing'],
 ['sm',
  'ac',
  'sptv',
  'the',
  'new',
  'jersey',
  'devil',
  'and',
  'the',
  'detroit',
  'red',
  'wing',
  'play',
  'ice',
  'hockey',
  'correct',
  'or',
  'incorrect',
  'end',
  'reply',
  'end',
  'sptv'],
 ['do',
  'you',
  'know',
  'what',
  'mallika',
  'sherawat',
  'did',
  'yesterday',
  'find',
  'out',
  'now',
  'lt',
  'url',
  'gt'],
 ['congrats',
  'year',
  'special',
  'cinema',
  'pas',
  'for',
  'is',
  'yours',
  'call',
  'now',
  'suprman',
  'matrix',
  'starwars',
  'etc',
  'all',
  'free',
  'bx',
  'ip',
  'we',
  'pm',
  'dont',
  'miss',
  'out'],
 ['sorry', 'll', 'call', 'later', 'in', 'meeting'],
 ['tell', 'where', 'you', 'reached'],
 ['yes', 'gauti', 'and', 'sehwag', 'out', 'of', 'odi', 'series'],
 ['your',
  'gonna',
  'have',
  'to',
  'pick',
  'up',
  'burger',
  'for',
  'yourself',
  'on',
  'your',
  'way',
  'home',
  'can',
  'even',
  'move',
  'pain',
  'is',
  'killing',
  'me'],
 ['ha', 'ha', 'ha', 'good', 'joke', 'girl', 'are', 'situation', 'seeker'],
 ['it', 'part', 'of', 'checking', 'iq'],
 ['sorry',
  'my',
  'roommate',
  'took',
  'forever',
  'it',
  'ok',
  'if',
  'come',
  'by',
  'now'],
 ['ok',
  'lar',
  'double',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'already',
  'he',
  'said',
  'wun',
  'cut',
  'short',
  'he',
  'said',
  'will',
  'cut',
  'until',
  'look',
  'nice'],
 ['valued',
  'customer',
  'am',
  'pleased',
  'to',
  'advise',
  'you',
  'that',
  'following',
  'recent',
  'review',
  'of',
  'your',
  'mob',
  'no',
  'you',
  'are',
  'awarded',
  'with',
  'bonus',
  'prize',
  'call'],
 ['today',
  'is',
  'song',
  'dedicated',
  'day',
  'which',
  'song',
  'will',
  'dedicate',
  'for',
  'me',
  'send',
  'this',
  'to',
  'all',
  'ur',
  'valuable',
  'frnds',
  'but',
  'first',
  'rply',
  'me'],
 ['urgent',
  'ur',
  'awarded',
  'complimentary',
  'trip',
  'to',
  'eurodisinc',
  'trav',
  'aco',
  'entry',
  'or',
  'to',
  'claim',
  'txt',
  'dis',
  'to',
  'morefrmmob',
  'aj'],
 ['did',
  'you',
  'hear',
  'about',
  'the',
  'new',
  'divorce',
  'barbie',
  'it',
  'come',
  'with',
  'all',
  'of',
  'ken',
  'stuff'],
 ['plane', 'to', 'give', 'on', 'this', 'month', 'end'],
 ['wah', 'lucky', 'man', 'then', 'can', 'save', 'money', 'hee'],
 ['finished', 'class', 'where', 'are', 'you'],
 ['hi', 'babe', 'im', 'at', 'home', 'now', 'wanna', 'do', 'something', 'xx'],
 ['where', 'are', 'you', 'how', 'did', 'you', 'performed'],
 ['can', 'call', 'me', 'now'],
 ['am', 'waiting', 'machan', 'call', 'me', 'once', 'you', 'free'],
 ['thats',
  'cool',
  'am',
  'gentleman',
  'and',
  'will',
  'treat',
  'you',
  'with',
  'dignity',
  'and',
  'respect'],
 ['like', 'you', 'people', 'very', 'much', 'but', 'am', 'very', 'shy', 'pa'],
 ['doe', 'not', 'operate', 'after', 'lt', 'gt', 'or', 'what'],
 ['it',
  'not',
  'the',
  'same',
  'here',
  'still',
  'looking',
  'for',
  'job',
  'how',
  'much',
  'do',
  'ta',
  'earn',
  'there'],
 ['sorry', 'll', 'call', 'later'],
 ['did', 'you', 'call', 'me', 'just', 'now', 'ah'],
 ['ok', 'am', 'on', 'the', 'way', 'to', 'home', 'hi', 'hi'],
 ['you', 'will', 'be', 'in', 'the', 'place', 'of', 'that', 'man'],
 ['yup', 'next', 'stop'],
 ['call', 'you', 'later', 'don', 'have', 'network', 'if', 'urgnt', 'sm', 'me'],
 ['for',
  'real',
  'when',
  'getting',
  'on',
  'yo',
  'only',
  'need',
  'more',
  'ticket',
  'and',
  'one',
  'more',
  'jacket',
  'and',
  'done',
  'already',
  'used',
  'all',
  'my',
  'multis'],
 ['yes',
  'started',
  'to',
  'send',
  'request',
  'to',
  'make',
  'it',
  'but',
  'pain',
  'came',
  'back',
  'so',
  'back',
  'in',
  'bed',
  'double',
  'coin',
  'at',
  'the',
  'factory',
  'too',
  'gotta',
  'cash',
  'in',
  'all',
  'my',
  'nitros'],
 ['really', 'not', 'up', 'to', 'it', 'still', 'tonight', 'babe'],
 ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['yeah',
  'do',
  'don',
  'stand',
  'to',
  'close',
  'tho',
  'you',
  'll',
  'catch',
  'something'],
 ['sorry',
  'to',
  'be',
  'pain',
  'is',
  'it',
  'ok',
  'if',
  'we',
  'meet',
  'another',
  'night',
  'spent',
  'late',
  'afternoon',
  'in',
  'casualty',
  'and',
  'that',
  'mean',
  'haven',
  'done',
  'any',
  'of',
  'stuff',
  'moro',
  'and',
  'that',
  'includes',
  'all',
  'my',
  'time',
  'sheet',
  'and',
  'that',
  'sorry'],
 ['smile',
  'in',
  'pleasure',
  'smile',
  'in',
  'pain',
  'smile',
  'when',
  'trouble',
  'pours',
  'like',
  'rain',
  'smile',
  'when',
  'sum',
  'hurt',
  'smile',
  'becoz',
  'someone',
  'still',
  'love',
  'to',
  'see',
  'smiling'],
 ['please',
  'call',
  'our',
  'customer',
  'service',
  'representative',
  'on',
  'between',
  'am',
  'pm',
  'you',
  'have',
  'won',
  'guaranteed',
  'cash',
  'or',
  'prize'],
 ['havent',
  'planning',
  'to',
  'buy',
  'later',
  'check',
  'already',
  'lido',
  'only',
  'got',
  'show',
  'in',
  'afternoon',
  'finish',
  'work',
  'already'],
 ['your',
  'free',
  'ringtone',
  'is',
  'waiting',
  'to',
  'be',
  'collected',
  'simply',
  'text',
  'the',
  'password',
  'mix',
  'to',
  'to',
  'verify',
  'get',
  'usher',
  'and',
  'britney',
  'fml',
  'po',
  'box',
  'mk',
  'ppw'],
 ['watching', 'telugu', 'movie', 'wat', 'abt'],
 ['see',
  'when',
  'we',
  'finish',
  'we',
  'have',
  'load',
  'of',
  'loan',
  'to',
  'pay'],
 ['hi',
  'wk',
  'been',
  'ok',
  'on',
  'hols',
  'now',
  'yes',
  'on',
  'for',
  'bit',
  'of',
  'run',
  'forgot',
  'that',
  'have',
  'hairdresser',
  'appointment',
  'at',
  'four',
  'so',
  'need',
  'to',
  'get',
  'home',
  'shower',
  'beforehand',
  'doe',
  'that',
  'cause',
  'prob',
  'for'],
 ['see', 'cup', 'of', 'coffee', 'animation'],
 ['please',
  'don',
  'text',
  'me',
  'anymore',
  'have',
  'nothing',
  'else',
  'to',
  'say'],
 ['okay',
  'name',
  'ur',
  'price',
  'long',
  'it',
  'legal',
  'wen',
  'can',
  'pick',
  'them',
  'up',
  'ave',
  'am',
  'xx'],
 ['still',
  'looking',
  'for',
  'car',
  'to',
  'buy',
  'and',
  'have',
  'not',
  'gone',
  'the',
  'driving',
  'test',
  'yet'],
 ['per',
  'your',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'ha',
  'been',
  'set',
  'your',
  'callertune',
  'for',
  'all',
  'caller',
  'press',
  'to',
  'copy',
  'your',
  'friend',
  'callertune'],
 ['wow',
  'you',
  're',
  'right',
  'didn',
  'mean',
  'to',
  'do',
  'that',
  'guess',
  'once',
  'gave',
  'up',
  'on',
  'boston',
  'men',
  'and',
  'changed',
  'my',
  'search',
  'location',
  'to',
  'nyc',
  'something',
  'changed',
  'cuz',
  'on',
  'my',
  'signin',
  'page',
  'it',
  'still',
  'say',
  'boston'],
 ['umma', 'my', 'life', 'and', 'vava', 'umma', 'love', 'you', 'lot', 'dear'],
 ['thanks',
  'lot',
  'for',
  'your',
  'wish',
  'on',
  'my',
  'birthday',
  'thanks',
  'you',
  'for',
  'making',
  'my',
  'birthday',
  'truly',
  'memorable'],
 ['aight', 'll', 'hit', 'you', 'up', 'when', 'get', 'some', 'cash'],
 ['how',
  'would',
  'my',
  'ip',
  'address',
  'test',
  'that',
  'considering',
  'my',
  'computer',
  'isn',
  'minecraft',
  'server'],
 ['know',
  'grumpy',
  'old',
  'people',
  'my',
  'mom',
  'wa',
  'like',
  'you',
  'better',
  'not',
  'be',
  'lying',
  'then',
  'again',
  'am',
  'always',
  'the',
  'one',
  'to',
  'play',
  'joke'],
 ['dont', 'worry', 'guess', 'he', 'busy'],
 ['what', 'is', 'the', 'plural', 'of', 'the', 'noun', 'research'],
 ['going', 'for', 'dinner', 'msg', 'you', 'after'],
 ['ok',
  'wif',
  'it',
  'co',
  'like',
  'try',
  'new',
  'thing',
  'but',
  'scared',
  'dun',
  'like',
  'mah',
  'co',
  'said',
  'not',
  'too',
  'loud'],
 ['gent',
  'we',
  'are',
  'trying',
  'to',
  'contact',
  'you',
  'last',
  'weekend',
  'draw',
  'show',
  'that',
  'you',
  'won',
  'prize',
  'guaranteed',
  'call',
  'claim',
  'code',
  'valid',
  'hr',
  'only',
  'ppm'],
 ['wa',
  'ur',
  'openin',
  'sentence',
  'very',
  'formal',
  'anyway',
  'fine',
  'too',
  'juz',
  'tt',
  'eatin',
  'too',
  'much',
  'puttin',
  'on',
  'weight',
  'haha',
  'so',
  'anythin',
  'special',
  'happened'],
 ['entered',
  'my',
  'cabin',
  'my',
  'pa',
  'said',
  'happy',
  'day',
  'bos',
  'felt',
  'special',
  'she',
  'askd',
  'me',
  'lunch',
  'after',
  'lunch',
  'she',
  'invited',
  'me',
  'to',
  'her',
  'apartment',
  'we',
  'went',
  'there'],
 ['you',
  'are',
  'winner',
  'have',
  'been',
  'specially',
  'selected',
  'receive',
  'or',
  'holiday',
  'flight',
  'inc',
  'speak',
  'to',
  'live',
  'operator',
  'claim',
  'min'],
 ['goodo',
  'yes',
  'we',
  'must',
  'speak',
  'friday',
  'egg',
  'potato',
  'ratio',
  'for',
  'tortilla',
  'needed'],
 ['hmm',
  'my',
  'uncle',
  'just',
  'informed',
  'me',
  'that',
  'he',
  'paying',
  'the',
  'school',
  'directly',
  'so',
  'pls',
  'buy',
  'food'],
 ['private',
  'your',
  'account',
  'statement',
  'for',
  'show',
  'unredeemed',
  'bonus',
  'point',
  'to',
  'claim',
  'call',
  'identifier',
  'code',
  'expires'],
 ['urgent',
  'your',
  'mobile',
  'no',
  'wa',
  'awarded',
  'bonus',
  'caller',
  'prize',
  'on',
  'this',
  'is',
  'our',
  'final',
  'try',
  'to',
  'contact',
  'call',
  'from',
  'landline',
  'box',
  'wr',
  'ppm'],
 ['here',
  'is',
  'my',
  'new',
  'address',
  'apple',
  'pair',
  'all',
  'that',
  'malarky'],
 ['today',
  'voda',
  'number',
  'ending',
  'are',
  'selected',
  'to',
  'receive',
  'award',
  'if',
  'you',
  'have',
  'match',
  'please',
  'call',
  'quoting',
  'claim',
  'code',
  'standard',
  'rate',
  'app'],
 ['am',
  'going',
  'to',
  'sao',
  'mu',
  'today',
  'will',
  'be',
  'done',
  'only',
  'at'],
 ['predict', 'wat', 'time', 'll', 'finish', 'buying'],
 ['good', 'stuff', 'will', 'do'],
 ['just',
  'so',
  'that',
  'you',
  'know',
  'yetunde',
  'hasn',
  'sent',
  'money',
  'yet',
  'just',
  'sent',
  'her',
  'text',
  'not',
  'to',
  'bother',
  'sending',
  'so',
  'it',
  'over',
  'you',
  'dont',
  'have',
  'to',
  'involve',
  'yourself',
  'in',
  'anything',
  'shouldn',
  'have',
  'imposed',
  'anything',
  'on',
  'you',
  'in',
  'the',
  'first',
  'place',
  'so',
  'for',
  'that',
  'apologise'],
 ['are', 'you', 'there', 'in', 'room'],
 ['hey',
  'girl',
  'how',
  'hope',
  'well',
  'me',
  'an',
  'del',
  'bak',
  'again',
  'long',
  'time',
  'no',
  'give',
  'me',
  'call',
  'sum',
  'time',
  'from',
  'lucyxx'],
 ['how', 'much', 'doe', 'it', 'cost'],
 ['home'],
 ['dear', 'will', 'call', 'tmorrow', 'pls', 'accomodate'],
 ['first', 'answer', 'my', 'question'],
 ['sunshine',
  'quiz',
  'wkly',
  'win',
  'top',
  'sony',
  'dvd',
  'player',
  'if',
  'know',
  'which',
  'country',
  'the',
  'algarve',
  'is',
  'in',
  'txt',
  'ansr',
  'to',
  'sp',
  'tyrone'],
 ['want',
  'get',
  'laid',
  'tonight',
  'want',
  'real',
  'dogging',
  'location',
  'sent',
  'direct',
  'ur',

In [ ]:
len(words), df.shape
## 5569 sentences ---> 3 removed

(5569, (5572, 2))

In [162]:
import gensim
##training Word2Vec model from scratch using words provided.
## words format [[w1,w2,....],[w45,w34.......]]
# Builds a vocabulary from words
# Initializes word vectors randomly
# Trains a neural network (CBOW by default)
# Learns embeddings only from your corpus

# Domain-specific embeddings (finance, medical, legal)

# Small to medium NLP projects


##Pretrained word2vec -->wv = api.load('word2vec-google-news-300')
#  Trained on billions of words
#  Excellent general semantics
#  Works well with small datasets
#  May miss domain-specific meaning
#  Large memory size
model1=gensim.models.Word2Vec(words)

In [102]:
model1.wv.index_to_key
## get vocab

['to',
 'you',
 'the',
 'and',
 'it',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'if',
 'will',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'day',
 'ok',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'she',
 'home',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'they',
 'later',
 'please',
 'any',
 'pls',
 'her',
 'ha',
 'did',
 'co',
 'msg',
 'been',
 'min',
 'an',
 'some',
 'dear',
 'night',
 'make',
 'who',
 'here',
 'message',
 'well',
 'say',
 'where',
 're',
 'thing',
 'much',
 'hope',
 'oh',
 'claim',
 'great',
 'hey',
 'him',
 'number',
 'give',
 'more',
 'too',
 'happy',
 'work',
 'friend',
 'wat',
 'had',
 'way',
 'yes',
 'www',
 've',
 'should',
 'let',
 'prize',
 'won',
 'right',
 'tomorrow',
 'already',
 'tone',
 'after',
 'said',
 'ask',
 'win',
 'doing',
 'amp',
 'cash',
 'life',
 'im',
 'yeah',
 'really',
 'babe',
 'why',
 'meet',
 'find',
 'them',
 'miss',
 'very',
 'morning',
 'last',
 'service',
 'year',
 'uk',
 'thanks',
 'care',
 'would',
 'anything',
 'com',
 'also',
 'nokia',
 'lol',
 'every',
 'feel',
 'keep',
 'pick',
 'sure',
 'sent',
 'contact',
 'urgent',
 'over',
 'something',
 'gud',
 'buy',
 'again',
 'before',
 'cant',
 'wait',
 'box',
 'place',
 'first',
 'his',
 'even',
 'guy',
 'someone',
 'help',
 'went',
 'wish',
 'nice',
 'were',
 'next',
 'tonight',
 'off',
 'show',
 'which',
 'soon',
 'word',
 'around',
 'money',
 'could',
 'customer',
 'many',
 'sleep',
 'chat',
 'late',
 'per',
 'ya',
 'sm',
 'always',
 'gonna',
 'wan',
 'leave',
 'down',
 'name',
 'lot',
 'other',
 'pm',
 'end',
 'dun',
 'told',
 'st',
 'person',
 'waiting',
 'special',
 'hello',
 'girl',
 'try',
 'fine',
 'month',
 'hour',
 'may',
 'minute',
 'coming',
 'heart',
 'haha',
 'people',
 'best',
 'th',
 'thk',
 'yet',
 'guaranteed',
 'smile',
 'same',
 'done',
 'getting',
 'god',
 'ppm',
 'thought',
 'use',
 'offer',
 'didn',
 'start',
 'holiday',
 'class',
 'stuff',
 'talk',
 'line',
 'mean',
 'bit',
 'man',
 'live',
 'car',
 'lunch',
 'cost',
 'few',
 'draw',
 'job',
 'finish',
 'problem',
 'never',
 'being',
 'plan',
 'ill',
 'house',
 'hr',
 'better',
 'cool',
 'thats',
 'meeting',
 'trying',
 'yup',
 'mind',
 'having',
 'ready',
 'dat',
 'account',
 'long',
 'pobox',
 'rate',
 'game',
 'weekend',
 'chance',
 'enjoy',
 'wk',
 'real',
 'half',
 'latest',
 'world',
 'than',
 'because',
 'sir',
 'bt',
 'guess',
 'po',
 'yo',
 'check',
 'play',
 'room',
 'pic',
 'voucher',
 'boy',
 'luv',
 'nothing',
 'wanna',
 'awarded',
 'sweet',
 'look',
 'eat',
 'camera',
 'receive',
 'lar',
 'shit',
 'big',
 'liao',
 'another',
 'into',
 'landline',
 'birthday',
 'ah',
 'dinner',
 'xxx',
 'quite',
 'ever',
 'kiss',
 'might',
 'video',
 'jus',
 'age',
 'land',
 'watch',
 'watching',
 'wont',
 'question',
 'probably',
 'orange',
 'two',
 'baby',
 'thanx',
 'called',
 'tv',
 'dream',
 'worry',
 'aight',
 'bed',
 'pa',
 'once',
 'hear',
 'nd',
 'speak',
 'fun',
 'early',
 'point',
 'princess',
 'bad',
 'den',
 'actually',
 'sat',
 'shall',
 'nite',
 'forgot',
 'part',
 'maybe',
 'ringtone',
 'doe',
 'left',
 'bus',
 'pay',
 'remember',
 'network',
 'apply',
 'office',
 'dunno',
 'made',
 'shopping',
 'reach',
 'easy',
 'between',
 'hurt',
 'code',
 'dad',
 'wife',
 'fuck',
 'put',
 'true',
 'didnt',
 'everything',
 'face',
 'leh',
 'evening',
 'little',
 'award',
 'anyway',
 'xx',
 'dis',
 'mate',
 'town',
 'gift',
 'sound',
 'working',
 'those',
 'mail',
 'yr',
 'school',
 'movie',
 'afternoon',
 'looking',
 'thank',
 'enough',
 'selected',
 'while',
 'detail',
 'asked',
 'collect',
 'tmr',
 'missing',
 'without',
 'most',
 'pound',
 'entry',
 'important',
 'hav',
 'xmas',
 'sexy',
 'join',
 'must',
 'price',
 'okay',
 'came',
 'pain',
 'since',
 'wanted',
 'valid',
 'though',
 'wif',
 'until',
 'collection',
 'bring',
 'wot',
 'book',
 'wake',
 'able',
 'til',
 'answer',
 'abt',
 'mob',
 'run',
 'missed',
 'lesson',
 'update',
 'plus',
 'away',
 'de',
 'change',
 'plz',
 'charge',
 'decimal',
 'stay',
 'juz',
 'test',
 'haven',
 'wen',
 'date',
 'colour',
 'attempt',
 'bored',
 'dude',
 'weekly',
 'music',
 'shop',
 'else',
 'havent',
 'hair',
 'double',
 'yesterday',
 'saw',
 'till',
 'alright',
 'lei',
 'goin',
 'online',
 'these',
 'drink',
 'friendship',
 'optout',
 'oso',
 'id',
 'coz',
 'haf',
 'top',
 'food',
 'making',
 'trip',
 'yours',
 'credit',
 'net',
 'family',
 'sch',
 'either',
 'feeling',
 'club',
 'hot',
 'gr',
 'smoke',
 'player',
 'address',
 'driving',
 'yourself',
 'delivery',
 'tried',
 'ard',
 'national',
 'sad',
 'together',
 'lose',
 'sae',
 'beautiful',
 'tot',
 'head',
 'post',
 'calling',
 'full',
 'ring',
 'wid',
 'walk',
 'both',
 'story',
 'si',
 'believe',
 'order',
 'nt',
 'busy',
 'bonus',
 'second',
 'mom',
 'http',
 'brother',
 'await',
 'drive',
 'saying',
 'mum',
 'eve',
 'poly',
 'huh',
 'chikku',
 'row',
 'happen',
 'noe',
 'sleeping',
 'hand',
 'leaving',
 'old',
 'smiling',
 'close',
 'info',
 'set',
 'drop',
 'rite',
 'email',
 'pub',
 'simple',
 'thinking',
 'suite',
 'mths',
 'okie',
 'wil',
 'awesome',
 'parent',
 'match',
 'private',
 'cause',
 'started',
 'finished',
 'took',
 'congrats',
 'tomo',
 'doesn',
 'aft',
 'news',
 'hl',
 'auction',
 'anyone',
 'neva',
 'mine',
 'gd',
 'reason',
 'valentine',
 'sister',
 'card',
 'unsubscribe',
 'angry',
 'company',
 'tc',
 'break',
 'touch',
 'content',
 'everyone',
 'taking',
 'statement',
 'forget',
 'tho',
 'caller',
 'final',
 'available',
 'alone',
 'loving',
 'gal',
 'knw',
 'sun',
 'whatever',
 'opt',
 'dating',
 'choose',
 'found',
 'worth',
 'carlos',
 'bank',
 'fancy',
 'each',
 'whats',
 'open',
 'type',
 'expires',
 'search',
 'ticket',
 'lucky',
 'treat',
 'hows',
 'party',
 'fast',
 'sub',
 'visit',
 'nyt',
 'kind',
 'welcome',
 'bout',
 'mobileupd',
 'far',
 'anytime',
 'congratulation',
 'secret',
 'gbp',
 'exam',
 'college',
 'boytoy',
 'frnd',
 'hard',
 'ltd',
 'ni',
 'quiz',
 'identifier',
 'uncle',
 'friday',
 'happened',
 'hit',
 'gone',
 'prob',
 'song',
 'decided',
 'saturday',
 'smth',
 'wonderful',
 'winner',
 'chennai',
 'least',
 'wrong',
 'lovely',
 'wonder',
 'drug',
 'sea',
 'pretty',
 'fri',
 'outside',
 'nope',
 'term',
 'fucking',
 'project',
 'light',
 'read',
 'hold',
 'tel',
 'oredi',
 'goodmorning',
 'darlin',
 'mrng',
 'finally',
 'wit',
 'mu',
 'operator',
 'used',
 'camcorder',
 'crazy',
 'wasn',
 'support',
 'earlier',
 'snow',
 'listen',
 'savamob',
 'frm',
 'cum',
 'ten',
 'jay',
 'fone',
 'blue',
 'unlimited',
 'cd',
 'fr',
 'meant',
 'case',
 'course',
 'log',
 'their',
 'hmm',
 'isn',
 'frnds',
 'whole',
 'telling',
 'seeing',
 'hungry',
 'wq',
 'sunday',
 'freemsg',
 'wkly',
 'father',
 'gas',
 'john',
 'enter',
 'luck',
 'film',
 'na',
 'gn',
 'knew',
 'understand',
 'store',
 'mayb',
 'sell',
 'sex',
 'paper',
 'area',
 'happiness',
 'yar',
 'un',
 'within',
 'park',
 'sk',
 'india',
 'as',
 'rock',
 'couple',
 'talking',
 'motorola',
 'moment',
 'currently',
 'ago',
 'txts',
 'reading',
 'christmas',
 'lost',
 'bslvyl',
 'die',
 'stupid',
 'single',
 'dnt',
 'side',
 'march',
 'balance',
 'mr',
 'hmmm',
 'joy',
 'tired',
 'invited',
 'felt',
 'mah',
 'computer',
 'load',
 'download',
 'hee',
 'cut',
 'move',
 'etc',
 'pas',
 'almost',
 'child',
 'eh',
 'valued',
 'press',
 'difficult',
 'grin',
 'surprise',
 'information',
 'heard',
 'photo',
 'sort',
 'extra',
 'ugh',
 'picking',
 'eye',
 'xy',
 'darren',
 'kid',
 'gym',
 'through',
 'max',
 'redeemed',
 'lady',
 'ipod',
 'doin',
 'supposed',
 'rental',
 'seen',
 'met',
 'ish',
 'figure',
 'via',
 'return',
 'ge',
 'swing',
 'laptop',
 'reveal',
 'bcoz',
 'semester',
 'bill',
 'direct',
 'sending',
 'askd',
 'shower',
 'gotta',
 'complimentary',
 'correct',
 'red',
 'ac',
 'wow',
 'hospital',
 'confirm',
 'charged',
 'promise',
 'comp',
 'police',
 'slowly',
 'loved',
 'fact',
 'fantasy',
 'nobody',
 'truth',
 'asap',
 'whenever',
 'idea',
 'laugh',
 'noon',
 'train',
 'door',
 'clean',
 'blood',
 'member',
 'rent',
 'monday',
 'remove',
 'asking',
 'yep',
 'slow',
 'discount',
 'hg',
 'ex',
 'weed',
 'small',
 'pete',
 'rest',
 'somebody',
 'hmv',
 'leaf',
 'wana',
 'own',
 'lover',
 'road',
 'study',
 'kate',
 'orchard',
 'bath',
 'muz',
 'safe',
 'wine',
 'lovable',
 'txting',
 'dogging',
 'entered',
 'page',
 'loan',
 'save',
 'rply',
 'checking',
 'joke',
 'crave',
 'abiola',
 'cheer',
 'comin',
 'eg',
 'link',
 'wap',
 'reward',
 'request',
 'usf',
 'std',
 'empty',
 'med',
 'hw',
 'cover',
 'write',
 'bb',
 'ringtones',
 'energy',
 'doctor',
 'convey',
 'rd',
 'sale',
 'cr',
 'ntt',
 'otherwise',
 'poor',
 'gettin',
 'bag',
 'getzed',
 'summer',
 'wishing',
 'glad',
 'fantastic',
 'gap',
 'king',
 'ho',
 'indian',
 'em',
 'cheap',
 'warm',
 'across',
 'hoping',
 'less',
 'opinion',
 'near',
 'water',
 'different',
 'booked',
 'wc',
 'ldn',
 'voice',
 'mm',
 'mistake',
 'woke',
 'rakhesh',
 'custcare',
 'immediately',
 'merry',
 'normal',
 'somewhere',
 'tonite',
 'usual',
 'deep',
 'admirer',
 'kick',
 'street',
 'teach',
 'deal',
 'bathe',
 'spend',
 'pray',
 'sony',
 'del',
 'men',
 'gave',
 'representative',
 'il',
 'short',
 'forever',
 'situation',
 'reached',
 'oops',
 'catch',
 'turn',
 ...]

In [103]:
'money' in model1.wv.index_to_key

True

In [104]:
'galaxy' in model1.wv.index_to_key
## word was not in the domain

False

In [163]:
model1.corpus_count

5569

In [107]:
model1.wv.similar_by_word('money')

[('big', 0.9993008375167847),
 ('any', 0.9992835521697998),
 ('had', 0.999239981174469),
 ('tonight', 0.9992197751998901),
 ('his', 0.9992108941078186),
 ('today', 0.999195396900177),
 ('after', 0.9991891980171204),
 ('wait', 0.9991880655288696),
 ('before', 0.9991627335548401),
 ('than', 0.9991508722305298)]

In [108]:
## now the format is for each sent --> multple vector 
## but we need single vector --> avg vec for every sentence

In [94]:
!pip install tqdm

Requirement already satisfied: tqdm in c:\users\karnaveer singh\desktop\decodingml\.venv\lib\site-packages (4.67.1)
Requirement already satisfied: colorama in c:\users\karnaveer singh\desktop\decodingml\.venv\lib\site-packages (from tqdm) (0.4.6)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [109]:
import numpy as np
## pass each sentence to this 
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    
    return np.mean([model1.wv[word] for word in doc if word in model1.wv.index_to_key],axis=0)
                #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [ ]:
# from tqdm import tqdm
import numpy as np
X=[]
for i in (range(len(words))):
    X.append(avg_word2vec(words[i]))

c:\Users\Karnaveer Singh\Desktop\DecodingML\.venv\Lib\site-packages\numpy\_core\fromnumeric.py:3860: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\Karnaveer Singh\Desktop\DecodingML\.venv\Lib\site-packages\numpy\_core\_methods.py:144: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

In [138]:
len(X[0])
## single vector of 100 dimention for each sentnence

100

In [139]:
print(type(X))
print(type(X[0]))
print(X[0].shape)

<class 'list'>
<class 'numpy.ndarray'>
(100,)

In [ ]:
bad_indices = []
# Some doc lists contain ZERO in-vocabulary words
## mean (nan,nan,nan...) = nan
for i, x in enumerate(X):
    if not hasattr(x, '__iter__'):
        bad_indices.append(i)

print("Bad indices:", bad_indices)

Bad indices: [451, 783, 2102, 2569, 3269, 3740, 3979, 4291, 4478, 4620, 5170, 5411]

In [142]:
X[451]

np.float64(nan)

In [147]:
X = [vector for vector in X if type(vector)!=np.float64]

In [148]:
bad_indices = []

for i, x in enumerate(X):
    if not hasattr(x, '__iter__'):
        bad_indices.append(i)

print("Bad indices:", bad_indices)

Bad indices: []

In [149]:
df1 = pd.DataFrame(X)

In [150]:
df1

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.168217,0.255117,0.076055,0.098778,0.076175,-0.520234,0.145810,0.492169,-0.283645,-0.104313,...,0.292674,0.115538,0.035386,0.137671,0.374080,0.305652,0.075083,-0.196133,0.141156,-0.086727
1,-0.150641,0.223921,0.063718,0.090415,0.066482,-0.468075,0.119137,0.441377,-0.242015,-0.079079,...,0.261727,0.095251,0.027653,0.116107,0.322749,0.261934,0.064286,-0.181716,0.117010,-0.075498
2,-0.161656,0.263562,0.099326,0.132192,0.077996,-0.581648,0.150653,0.506892,-0.305237,-0.115630,...,0.294387,0.127359,0.026142,0.148681,0.396305,0.293252,0.056013,-0.223684,0.170655,-0.085177
3,-0.238603,0.355689,0.097901,0.134065,0.103454,-0.709939,0.198218,0.686802,-0.394570,-0.135462,...,0.407172,0.149262,0.042827,0.187658,0.500115,0.421842,0.104846,-0.279124,0.184705,-0.109989
4,-0.205460,0.296193,0.085713,0.108975,0.095748,-0.595045,0.161230,0.579612,-0.329412,-0.121474,...,0.346695,0.121591,0.040476,0.157522,0.421183,0.354363,0.086269,-0.239191,0.157205,-0.104176
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5552,-0.192802,0.314554,0.115972,0.142902,0.093172,-0.659223,0.183275,0.585946,-0.352745,-0.140758,...,0.347679,0.147578,0.032732,0.159747,0.467657,0.346940,0.073329,-0.254240,0.198700,-0.095201
5553,-0.216354,0.299466,0.094828,0.125707,0.106555,-0.640009,0.171188,0.613318,-0.355547,-0.123214,...,0.366058,0.139377,0.032589,0.169350,0.453158,0.373767,0.083139,-0.250252,0.173221,-0.101764
5554,-0.231521,0.356435,0.098604,0.124902,0.098781,-0.692216,0.195797,0.667929,-0.378868,-0.142523,...,0.400759,0.156525,0.048719,0.188401,0.506590,0.417944,0.106978,-0.258856,0.191018,-0.118896
5555,-0.205190,0.313383,0.093987,0.120778,0.093403,-0.631447,0.172271,0.598134,-0.343918,-0.129402,...,0.355302,0.137048,0.049156,0.166403,0.455682,0.368492,0.085698,-0.240293,0.173254,-0.108829
5556,-0.238368,0.339105,0.094165,0.125289,0.107767,-0.686481,0.185047,0.666261,-0.383013,-0.144043,...,0.394837,0.139349,0.054380,0.179483,0.489063,0.407850,0.096532,-0.269114,0.191745,-0.110626

In [ ]:
y

array([ True,  True, False, ...,  True,  True,  True], shape=(5572,))

In [155]:
len(df1),len(y)

(5557, 5572)

In [165]:
texts = df['text'].tolist()
y = df['label'].tolist()

In [166]:
corpus = []
for text in texts:
    review = re.sub('[^a-zA-Z]', ' ', text)
    review = review.lower().split()
    review = [lemmatizer.lemmatize(word) for word in review]
    corpus.append(review)   # KEEP AS LIST, not string

In [167]:
indexed_words = []

for i, doc in enumerate(corpus):
    if len(doc) > 0:
        indexed_words.append((i, simple_preprocess(" ".join(doc))))

In [ ]:
## do splitting first then vectorizing 

words_only = [w for _, w in indexed_words]
model1 = gensim.models.Word2Vec(words_only, vector_size=100)

In [169]:
def avg_word2vec(doc):
    vectors = [model1.wv[word] for word in doc if word in model1.wv.index_to_key]
    if len(vectors) == 0:
        return None
    return np.mean(vectors, axis=0)

In [181]:
X = []
y_clean = []
text_clean = []

for idx, doc in indexed_words:
    vec = avg_word2vec(doc)
    if vec is not None:
        X.append(vec)
        y_clean.append(y[idx])
        text_clean.append(texts[idx])

In [182]:
assert len(X) == len(y_clean) == len(text_clean)

In [183]:
df1 = pd.DataFrame(X)

In [184]:
y_clean = pd.get_dummies(y_clean,drop_first=True,dtype=int)

In [185]:
df1['output']=y_clean

In [186]:
df1.head()

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,output
0,-0.172649,0.255656,0.073831,0.122629,0.068735,-0.542106,0.131298,0.468441,-0.309553,-0.071912,...,0.150509,0.020980,0.139858,0.342729,0.322501,0.075919,-0.201505,0.128898,-0.081123,0
1,-0.146388,0.216860,0.057854,0.108111,0.054631,-0.468390,0.102779,0.405914,-0.258292,-0.045641,...,0.124829,0.016415,0.117553,0.289698,0.267939,0.063748,-0.179175,0.103426,-0.069287,0
2,-0.167008,0.274175,0.101028,0.153613,0.070254,-0.599358,0.145710,0.473985,-0.324311,-0.081489,...,0.161738,0.001640,0.141675,0.360244,0.312887,0.052229,-0.225113,0.155531,-0.084007,1
3,-0.237895,0.343004,0.089777,0.165102,0.089161,-0.717669,0.166893,0.637888,-0.423463,-0.086834,...,0.195198,0.025768,0.192398,0.446661,0.434432,0.103553,-0.281928,0.162176,-0.098291,0
4,-0.207812,0.286964,0.081514,0.134511,0.088032,-0.603468,0.135361,0.540442,-0.357227,-0.080900,...,0.161033,0.025234,0.159050,0.374244,0.368859,0.084322,-0.246342,0.139298,-0.090610,0

In [187]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df1.drop(columns=['output']),df1['output'],test_size=0.20)

In [188]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
266,-0.146249,0.208256,0.057607,0.103028,0.055562,-0.442009,0.100910,0.387943,-0.256463,-0.056151,...,0.232065,0.120626,0.011239,0.113139,0.274489,0.260086,0.063442,-0.169295,0.099886,-0.068470
3782,-0.235455,0.307085,0.090016,0.122207,0.110544,-0.635171,0.128288,0.579560,-0.381574,-0.097929,...,0.360385,0.163182,0.035753,0.146184,0.378411,0.407568,0.092051,-0.272328,0.147701,-0.082652
4574,-0.238104,0.366251,0.104368,0.170333,0.093108,-0.757250,0.182615,0.658861,-0.428348,-0.106635,...,0.393186,0.211388,0.031953,0.195289,0.481375,0.447942,0.106958,-0.277779,0.184925,-0.121168
962,-0.201442,0.273881,0.074302,0.117773,0.081281,-0.570614,0.130190,0.508386,-0.334344,-0.081127,...,0.311058,0.154674,0.031426,0.143846,0.353264,0.357977,0.089811,-0.223881,0.135874,-0.080643
5452,-0.205485,0.315654,0.111612,0.165367,0.086628,-0.691213,0.160430,0.565447,-0.375694,-0.093804,...,0.338155,0.190136,0.014971,0.167332,0.421127,0.379290,0.073094,-0.257317,0.173394,-0.099794

In [190]:

from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [191]:
classifier.fit(X_train,y_train)
y_pred=classifier.predict(X_test)

from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(y_test,y_pred))

0.9685251798561151